analyzer:
  errors:
    deprecated_member_use: ignore
    avoid_print: ignore
    unused_local_variable: ignore
    use_super_parameters: ignore
    empty_catches: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
